
version: '3'
services:
  artzitrus:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: artzitrus/api
    ports:
      - '8080:8080'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    depends_on:
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=artzitrus
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql